name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FRONTEND_IMAGE: amayuru/leonsapp-frontend
      BACKEND_IMAGE: amayuru/leonsapp-backend
      GIT_REPO: https://github.com/Leon-s-Kitchen/Leon-s-Kitchen-Web.git

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Frontend Docker image
      run: docker build -t $FRONTEND_IMAGE:${{ github.run_number }} ./Frontend

    - name: Build Backend Docker image
      run: docker build -t $BACKEND_IMAGE:${{ github.run_number }} ./Backend

    - name: Push Frontend Docker image
      run: docker push $FRONTEND_IMAGE:${{ github.run_number }}

    - name: Push Backend Docker image
      run: docker push $BACKEND_IMAGE:${{ github.run_number }}

    - name: Log out from Docker Hub
      run: docker logout

